media:
  input: public/media
  output: /media

content:
  - name: offers
    label: عروض الرحلات
    type: file
    path: content/offers.json
    fields:
      - name: title
        label: اسم الرحلة
        type: string
      - name: price
        label: السعر
        type: string
      - name: desc
        label: تفاصيل العرض
        type: string
      - name: image
        label: صورة الرحلة
        type: image
